package com.datamatcher.server.entities;

public enum DataType {
    JSON, DEFAULT_CSV, MONGODB_CSV, MONGODB_TSV, EXCEL, INFORMIX_UNLOAD,
    INFORMIX_UNLOAD_CSV, TDF, MYSQL, ORACLE, POSTGRESQL_CSV,
    POSTGRESQL_TEXT, RFC4180, AUTODETECT
}
